### ISSUE TITLE
Stuff to-do

### ISSUE THREAD

**Issue by jkingstonc** [kng-ecosystem/compiler#1]
There is a lot to do... this is a checklist of to-do that will be regularly updated!

- [x] block scopes cause "symbol already defined" error with same variable names
- [ ] passing variables as arguments causes a "symbol already defined" error
- [ ] pointers still don't work, LLVM tries to dereference them when passing them around?
- [ ] imports
- [ ] interfaces
- [x] fn calls with multiple args don't 
- [ ] all mathematical operators
- [ ] if 2 string constants are the same, they should share the same memory, but currently separate are allocated
- [x] when using variable expressions (not assigned to them) should create a load e.g. printf(x) instead of a store
- [ ] parse ptr assignments (assignment lhs should be an expression)
- [x] fix reassignment of pointer types such as arrays
- [x] u8 ptr should match string type
- [ ] array constants should be globally assigned
- [ ] fn calls with multiple args should be patterns
- [ ] fn params support variadic
- [ ] for loops
- [ ] conditional branching
